# Default values for app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  repository: cr.yandex/crpr9jlf6k4254l80050/pidor_bot
  version: 107-d753f14ac4bbe40d92bc7450c925e5fbef76d245

# Game configuration (replaces CHAT_WHITELIST and TEST_CHAT_ID)
gameConfig:
  enabled_chats:
    - -1001392307997
    - -4608252738
    - -1002189152002
    - -1003671793100
  test_chat_id: -4608252738
  defaults: {}
  chat_overrides:
    "-4608252738":
      max_missed_days_for_final_voting: 100
